<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Shape;

/**
 * ShapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShapeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getShapeBy($type, $size)
    {
        return $this->findOneBy([
            'type' => $type,
            'size' => $size
        ]);
    }

    public function getShapeRandom()
    {
        return $this->findOneBy([
            'type' => array_rand(Shape::$type_list),
            'size' => array_rand(Shape::$size_list)
        ]);
    }
}
